#! /bin/sh
set -e

sd=$1
img=$2

usage() {
	echo "$0 /dev/sdX img.tar.gz"
}

if [ ! -b $sd ]; then
	usage
	exit 2
fi

if [ ! -f $img ]; then
	usage
	exit 2
fi

echo "Formating partitions ..."
echo "
o
p
n
p
1

+100M
t
c

n
p
2

+1G

n
p
3

+1G

n
p


w
" | fdisk $sd
sleep 3

mkfs.vfat ${sd}1
mkdir -p boot
mount ${sd}1 boot

mkfs.ext4 ${sd}2
mkdir -p root
mount ${sd}2 root

mkfs.ext4 ${sd}3
mkdir -p backuproot
mount ${sd}3 backuproot

mkfs.ext4 ${sd}4
mkdir -p user
mount ${sd}4 user

echo "Installing root..."
bsdtar -xpf $img  -C root --exclude=/boot/* --exclude=/etc/* --exclude=/usr/* --exclude=/home/*
sync

echo "Installing boot..."
bsdtar -xpf $img boot

echo "Finishing"
umount boot root backuproot user

echo "Done"
