#! /bin/sh
set -e

sd=$1
img=$2

usage() {
	echo "$0 /dev/sdX img.tar.gz"
}

if [ ! -b $sd ]; then
	usage
	exit 2
fi

if [ ! -f $img ]; then
	usage
	exit 2
fi

echo "Formating partitions ..."
echo "
o
p
n
p
1

+100M
t
c

n
p
2


w
" | fdisk $sd
sleep 3

mkfs.vfat ${sd}1
mkdir -p boot
mount ${sd}1 boot

mkfs.ext4 ${sd}2
mkdir -p root
mount ${sd}2 root

echo "Installing root..."
bsdtar -xpf $img  -C root --exclude ./boot
sync

echo "Installing boot..."
bsdtar -xpf $img boot

echo "Finishing"
umount boot root

echo "Done"
